### ISSUE TITLE
有关于不使用 pm2 进行部署的问题

### ISSUE THREAD

**Issue by kernelbin** [windowsair/fzu-cpDailySign#14]
在 README 中有提到如果不使用 pm2 进行部署需要修改 `cronSignTask`：

> 如果不使用pm2进行部署,需要修改cronSignTask中的相关内容.具体见utils.js

但 repo 中似乎并没有包含 `cronSignTask` 的任何代码，我只在部分文件的历史记录里找到了 `cronSignTask`。请问现在是否仍然需要修改相关内容，以及如何修改。谢谢！

非常感谢，这个项目在 `auto-sign` 不能使用之后再次解放了我

**Comment by windowsair** [comment]
原本是为了防止定时任务同时触发的，现在暂时不用修改。

如果用其他方法部署有问题你再反馈。
