### ISSUE TITLE
关于如何查看日志的问题

### ISSUE THREAD

**Issue by HongjieCN** [windowsair/fzu-cpDailySign#15]
![image](https://user-images.githubusercontent.com/57511284/149673979-9e26aed8-e91a-4791-b1c2-8b5432da1305.png)
如图，显示两条错误，具体的表现为打卡设置里面的开关会保存，但是地址信息不保存，推送测试成功但是显示空白错误框，推测是数据库连接的问题。我的数据库使用的是redis的docker版，版本为6.2.6，在本地机测试无问题，但是在服务器测试有问题，请问在哪里查看日志？谢谢

**Comment by windowsair** [comment]
和部署方式有关，用pm2部署的可以通过pm2 log查看

显示空白数据框可能是bug，用f12调出开发者工具，看看网络请求是啥样的

**Comment by HongjieCN** [comment]
谢谢你作者，通过你的方法我确实看到了昨天测试时pm2报错没有连接到redis服务器的问题，现在已经解决，并且可以查询到历史记录，如果历史记录是存储在redis的话，那说明redis已经可用了。
![image](https://user-images.githubusercontent.com/57511284/149699944-b6893efc-48fb-4c7b-ad6c-04df2273b74a.png)
我测试了QMSG的推送测试，是可以提示测试成功的，测试显示空白应该是ServerChan推送返回存在问题。
![image](https://user-images.githubusercontent.com/57511284/149700324-f245c227-2fd0-4da7-a25b-c62e12493032.png)
![image](https://user-images.githubusercontent.com/57511284/149700483-4436287a-7ea9-461c-831a-628730881098.png)
但是使用另一个浏览器查看同账号的签到设置时，仅有按钮状态显示，地址和经纬度不显示，同时推送方式显示为空，但是历史记录可以显示。请问这是一种策略吗？或者说是我配置的问题，因为我在本地测试是一样的情况。

**Comment by windowsair** [comment]
是的，是一种策略，不会返回任何的地址位置信息。

ServerChan已经很久没更新了，我现在看看有啥问题

**Comment by windowsair** [comment]
对，确实是我的问题，现在已经修复了

**Comment by HongjieCN** [comment]
谢谢作者解答！我看了F12，那两条错误提示是来自于调用CRON接口的，返回了404
![image](https://user-images.githubusercontent.com/57511284/149703092-d1d09736-9bb5-46a3-9015-bf969796d94f.png)
在本地和服务器测试结果是一样的，但是实际好像并没有影响功能

**Comment by windowsair** [comment]
用来显示系统公告和更新时间的，不影响主要功能

**Comment by HongjieCN** [comment]
谢谢作者解答！感谢作者付出！
