### ISSUE TITLE
8.2.24版本的密钥问题

### ISSUE THREAD

**Issue by qingcheng123** [windowsair/fzu-cpDailySign#5]
请问8.2.24版本的密钥的密钥是多少

**Comment by windowsair** [comment]
https://github.com/windowsair/fzu-cpDailySign/commit/9bfd007be015c2bd1a11e690635246184eda240a

看这个，加密方式有变

**Comment by qingcheng123** [comment]
9bfd007是新的密钥吗，我之前用的python的版本，8.2.24版本密钥好像变了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月19日(星期三) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windowsair/fzu-cpDailySign] 8.2.24版本的密钥问题 (#5)

**Comment by windowsair** [comment]
那是一个链接。。。
另，您所说的python版本大概率是云端版本，和本项目区别较大

**Comment by qingcheng123** [comment]
哦哦，这个是只针对福州大学的么？我一会先看看这个密钥可行------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月19日(星期三) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windowsair/fzu-cpDailySign] 8.2.24版本的密钥问题 (#5)

**Comment by windowsair** [comment]
是的

**Comment by qingcheng123** [comment]
谢谢您的回复！！------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月19日(星期三) 下午5:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [windowsair/fzu-cpDailySign] 8.2.24版本的密钥问题 (#5)
